dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	
	implementation 'com.mysql:mysql-connector-j'

	// lib
	implementation project(':lib:event-core')
	implementation project(':lib:event-starter')
	implementation project(':lib:web-swagger')
}
