dependencies {
    api project(':lib:security-core')
    api project(':lib:web-core')
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'jakarta.servlet:jakarta.servlet-api'
}

test {
    useJUnitPlatform()
}
