dependencies {
    api project(':lib:common-core')
    api project(':lib:redis-core')
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
}

test {
    useJUnitPlatform()
}
